server:
  port: 8081
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://172.16.100.10:5432/mkmClient_db_local
    username: admin
    password: secret